### ISSUE TITLE
import failing if field contains more than 255 chars

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/tomato#80]
nerna had failed import from train line field having more than 255 chars

22:33:04
importing root server https://www.nerna.org/main_server/

22:33:04
importing service bodies

22:33:05
importing formats

22:33:05
importing meetings

22:33:12
Error saving meeting: value too long for type character varying(255)

22:33:12
Encountered DatabaseError, closing database connection

22:33:12
Traceback (most recent call last):

22:33:12
File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 84, in _execute

22:33:12
return self.cursor.execute(sql, params)

22:33:12
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(255)

22:33:12
The above exception was the direct cause of the following exception:

22:33:12
Traceback (most recent call last):

22:33:12
File "/code/tomato/api/models.py", line 387, in import_from_bmlt_objects

22:33:12
meeting.meetinginfo.save()

22:33:12
File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 741, in save

22:33:12
force_update=force_update, update_fields=update_fields)

22:33:12
File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 779, in save_base

22:33:12
force_update, using, update_fields,

22:33:12
File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 851, in _save_table

22:33:12
forced_update)

22:33:12
File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 900, in _do_update

22:33:12
return filtered._update(values) > 0

22:33:12
File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 760, in _update

22:33:12
return query.get_compiler(self.db).execute_sql(CURSOR)

22:33:12
File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/compiler.py", line 1429, in execute_sql

22:33:12
cursor = super().execute_sql(result_type)

22:33:12
File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql

22:33:12
cursor.execute(sql, params)

22:33:12
File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 67, in execute

22:33:12
return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

22:33:12
File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers

22:33:12
return executor(sql, params, many, context)

22:33:12
File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 84, in _execute

22:33:12
return self.cursor.execute(sql, params)

22:33:12
File "/usr/local/lib/python3.6/dist-packages/django/db/utils.py", line 89, in __exit__

22:33:12
raise dj_exc_value.with_traceback(traceback) from exc_value

22:33:12
File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 84, in _execute

22:33:12
return self.cursor.execute(sql, params)

22:33:12
django.db.utils.DataError: value too long for type character varying(255)

22:33:12
During handling of the above exception, another exception occurred:

22:33:12
Traceback (most recent call last):

22:33:12
File "/code/tomato/api/management/commands/import_root_servers.py", line 127, in handle

22:33:12
self.update_meetings(root)

22:33:12
File "/code/tomato/api/management/commands/import_root_servers.py", line 202, in update_meetings

22:33:12
Meeting.import_from_bmlt_objects(root, meetings)

22:33:12
File "/code/tomato/api/models.py", line 397, in import_from_bmlt_objects

22:33:12
ImportProblem.objects.create(root_server=root_server, message=message, data=str(bmlt_meeting))

22:33:12
File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 250, in __repr__

22:33:12
data = list(self[:REPR_OUTPUT_SIZE + 1])

22:33:12
File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 274, in __iter__

22:33:12
self._fetch_all()

22:33:12
File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 1242, in _fetch_all

22:33:12
self._result_cache = list(self._iterable_class(self))

22:33:12
File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 55, in __iter__

22:33:12
results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)

22:33:12
File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql

22:33:12
cursor.execute(sql, params)

22:33:12
File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 67, in execute

22:33:12
return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

22:33:12
File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers

22:33:12
return executor(sql, params, many, context)

22:33:12
File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 79, in _execute

22:33:12
self.db.validate_no_broken_transaction()

22:33:12
File "/usr/local/lib/python3.6/dist-packages/django/db/backends/base/base.py", line 438, in validate_no_broken_transaction

22:33:12
"An error occurred in the current transaction. You can't "

22:33:12
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

**Comment by jbraswell** [comment]
Not going to fix this in tomato. We should limit the length of these fields to something more reasonable in the root server.
